Time::DATE_FORMATS[:friendly_long] = '%b %e, %Y at %l:%M%P'
Time::DATE_FORMATS[:interval] = '%l:%M%P'
Date::DATE_FORMATS[:long_with_wday] = '%a, %B %e, %Y'
Date::DATE_FORMATS[:short] = '%b %-d, %Y'
Date::DATE_FORMATS[:long] = '%B %-d, %Y'
# Date::DATE_FORMATS[:input] = '%Y/%m/%d'