---
- name: Install Nginx, Ruby, Passenger, UFW, Postgres, Redis, Postfix, enable swap volume.
  hosts: all
  # remote_user: "{{ lookup('env', 'USER') }}"
  sudo: yes
  vars:
    - nginx_version: 1.6.2
    - ruby_major_version: 2
    - ruby_minor_version: 2
    - ruby_patch_version: 0
    - ssh_user: "{{ lookup('env', 'USER') }}"

  roles:
    - swap
    - ufw
    - common
    - postgres
    - redis
    - postfix
    - ruby
    - passenger